import { DetectorResult } from "./types";

export const techMap: Record<string, DetectorResult> = {
  'typescript': { name: 'TypeScript', logo: 'typescript.svg', type: 'language' },
  'javascript': { name: 'JavaScript', logo: 'javascript.svg', type: 'language' },
  'python': { name: 'Python', logo: 'python.svg', type: 'language' },
  'go': { name: 'Go', logo: 'go.svg', type: 'language' },
  'rust': { name: 'Rust', logo: 'rust.svg', type: 'language' },
  'php': { name: 'PHP', logo: 'php.svg', type: 'language' },
  'ruby': { name: 'Ruby', logo: 'ruby.svg', type: 'language' },
  'java': { name: 'Java', logo: 'openjdk.svg', type: 'language' },
  'csharp': { name: 'C#', logo: 'csharp.svg', type: 'language' },
  'react': { name: 'React', logo: 'react.svg', type: 'frontend' },
  'react-dom': { name: 'ReactDOM', logo: 'react.svg', type: 'frontend' },
  'next': { name: 'Next.js', logo: 'nextdotjs.svg', type: 'frontend' },
  'remix': { name: 'Remix', logo: 'remix.svg', type: 'frontend' },
  'astro': { name: 'Astro', logo: 'astro.svg', type: 'frontend' },
  'svelte': { name: 'Svelte', logo: 'svelte.svg', type: 'frontend' },
  '@sveltejs/kit': { name: 'SvelteKit', logo: 'svelte.svg', type: 'frontend' },
  'solid-js': { name: 'SolidJS', logo: 'solid.svg', type: 'frontend' },
  'preact': { name: 'Preact', logo: 'preact.svg', type: 'frontend' },
  'vue': { name: 'Vue', logo: 'vuedotjs.svg', type: 'frontend' },
  'nuxt': { name: 'Nuxt', logo: 'nuxt.svg', type: 'frontend' },
  '@angular/core': { name: 'Angular', logo: 'angular.svg', type: 'frontend' },
  'lit': { name: 'Lit', logo: 'lit.svg', type: 'frontend' },
  '@builder.io/qwik': { name: 'Qwik', logo: 'qwik.svg', type: 'frontend' },
  'ember-source': { name: 'Ember', logo: 'emberdotjs.svg', type: 'frontend' },
  'backbone': { name: 'Backbone', logo: 'backbone.svg', type: 'frontend' },
  'alpinejs': { name: 'AlpineJS', logo: 'alpinedotjs.svg', type: 'frontend' },
  'htmx.org': { name: 'HTMX', logo: 'htmx.svg', type: 'frontend' },
  'tailwindcss': { name: 'TailwindCSS', logo: 'tailwindcss.svg', type: 'css' },
  'bootstrap': { name: 'Bootstrap', logo: 'bootstrap.svg', type: 'css' },
  'bulma': { name: 'Bulma', logo: 'bulma.svg', type: 'css' },
  'foundation-sites': { name: 'Foundation', logo: 'foundation.svg', type: 'css' },
  '@mui/material': { name: 'Material UI', logo: 'mui.svg', type: 'css' },
  '@chakra-ui/react': { name: 'Chakra UI', logo: 'chakraui.svg', type: 'css' },
  '@mantine/core': { name: 'Mantine', logo: 'fallback/mantine-logo.svg', type: 'css' },
  'shadcn': { name: 'ShadCN UI', logo: 'fallback/shadcnui.svg', type: 'css' },
  'daisyui': { name: 'DaisyUI', logo: 'daisyui.svg', type: 'css' },
  'antd': { name: 'Ant Design', logo: 'antdesign.svg', type: 'css' },
  '@radix-ui/react': { name: 'Radix UI', logo: 'radixui.svg', type: 'css' },
  '@headlessui/react': { name: 'Headless UI', logo: 'headlessui.svg', type: 'css' },
  '@emotion/react': { name: 'Emotion', logo: 'emotion.svg', type: 'css' },
  'styled-components': { name: 'Styled Components', logo: 'styledcomponents.svg', type: 'css' },
  '@stitches/react': { name: 'Stitches', logo: 'fallback/stitches.svg', type: 'css' },
  'sass': { name: 'Sass', logo: 'sass.svg', type: 'css' },
  'less': { name: 'Less', logo: 'less.svg', type: 'css' },
  'postcss': { name: 'PostCSS', logo: 'postcss.svg', type: 'css' },
  'redux': { name: 'Redux', logo: 'redux.svg', type: 'state' },
  'mobx': { name: 'MobX', logo: 'mobx.svg', type: 'state' },
  'zustand': { name: 'Zustand', logo: 'zustand.svg', type: 'state' },
  'jotai': { name: 'Jotai', logo: 'jotai.svg', type: 'state' },
  'recoil': { name: 'Recoil', logo: 'recoil.svg', type: 'state' },
  'xstate': { name: 'XState', logo: 'xstate.svg', type: 'state' },
  '@tanstack/react-query': { name: 'TanStack Query', logo: 'fallback/reactquery.svg', type: 'state' },
  '@reduxjs/toolkit': { name: 'RTK Query', logo: 'redux.svg', type: 'state' },
  'vite': { name: 'Vite', logo: 'vite.svg', type: 'build' },
  'webpack': { name: 'Webpack', logo: 'webpack.svg', type: 'build' },
  'parcel-bundler': { name: 'Parcel', logo: 'parcel.svg', type: 'build' },
  'rollup': { name: 'Rollup', logo: 'rollupdotjs.svg', type: 'build' },
  'snowpack': { name: 'Snowpack', logo: 'snowpack.svg', type: 'build' },
  'turbopack': { name: 'Turbopack', logo: 'webpack.svg', type: 'build' },
  '@swc/core': { name: 'SWC', logo: 'swc.svg', type: 'build' },
  'esbuild': { name: 'ESBuild', logo: 'esbuild.svg', type: 'build' },
  '@babel/core': { name: 'Babel', logo: 'babel.svg', type: 'build' },
  'tsup': { name: 'Tsup', logo: 'tsup.svg', type: 'build' },
  'jest': { name: 'Jest', logo: 'jest.svg', type: 'testing' },
  '@playwright/test': { name: 'Playwright', logo: 'playwright.svg', type: 'testing' },
  'cypress': { name: 'Cypress', logo: 'cypress.svg', type: 'testing' },
  'vitest': { name: 'Vitest', logo: 'vitest.svg', type: 'testing' },
  'mocha': { name: 'Mocha', logo: 'mocha.svg', type: 'testing' },
  'chai': { name: 'Chai', logo: 'chai.svg', type: 'testing' },
  '@testing-library/react': { name: 'Testing Library', logo: 'testinglibrary.svg', type: 'testing' },
  'jasmine': { name: 'Jasmine', logo: 'jasmine.svg', type: 'testing' },
  'puppeteer': { name: 'Puppeteer', logo: 'puppeteer.svg', type: 'testing' },
  '@storybook/react': { name: 'Storybook', logo: 'storybook.svg', type: 'testing' },
  'express': { name: 'Express', logo: 'express.svg', type: 'backend' },
  'fastify': { name: 'Fastify', logo: 'fastify.svg', type: 'backend' },
  '@nestjs/core': { name: 'NestJS', logo: 'nestjs.svg', type: 'backend' },
  'koa': { name: 'Koa', logo: 'koa.svg', type: 'backend' },
  '@hapi/hapi': { name: 'Hapi', logo: 'hapi.svg', type: 'backend' },
  'bun': { name: 'Bun', logo: 'bun.svg', type: 'runtime' },
  'deno': { name: 'Deno', logo: 'deno.svg', type: 'runtime' },
  '@adonisjs/core': { name: 'AdonisJS', logo: 'adonisjs.svg', type: 'backend' },
  '@feathersjs/feathers': { name: 'FeatherJS', logo: 'feather.svg', type: 'backend' },
  '@trpc/server': { name: 'tRPC', logo: 'trpc.svg', type: 'api' },
  'graphql-yoga': { name: 'GraphQL Yoga', logo: 'graphql.svg', type: 'api' },
  'apollo-server': { name: 'Apollo Server', logo: 'apollographql.svg', type: 'api' },
  'graphql': { name: 'GraphQL', logo: 'graphql.svg', type: 'api' },
  '@apollo/client': { name: 'Apollo Client', logo: 'apollographql.svg', type: 'api' },
  'urql': { name: 'Urql', logo: 'graphql.svg', type: 'api' },
  'relay-runtime': { name: 'Relay', logo: 'relay.svg', type: 'api' },
  '@graphql-codegen/cli': { name: 'GraphQL Codegen', logo: 'graphql.svg', type: 'api' },
  'prisma': { name: 'Prisma', logo: 'prisma.svg', type: 'orm' },
  'mongoose': { name: 'Mongoose', logo: 'mongoose.svg', type: 'orm' },
  'typeorm': { name: 'TypeORM', logo: 'typeorm.svg', type: 'orm' },
  'drizzle-orm': { name: 'Drizzle ORM', logo: 'fallback/Drizzle--Streamline-Simple-Icons.svg', type: 'orm' },
  'pg': { name: 'PostgreSQL', logo: 'postgresql.svg', type: 'database' },
  'mysql': { name: 'MySQL', logo: 'mysql.svg', type: 'database' },
  'mysql2': { name: 'MySQL', logo: 'mysql.svg', type: 'database' },
  'mariadb': { name: 'MariaDB', logo: 'mariadb.svg', type: 'database' },
  'sqlite3': { name: 'SQLite', logo: 'sqlite.svg', type: 'database' },
  'mongodb': { name: 'MongoDB', logo: 'mongodb.svg', type: 'database' },
  'redis': { name: 'Redis', logo: 'redis.svg', type: 'database' },
  '@elastic/elasticsearch': { name: 'Elasticsearch', logo: 'elasticsearch.svg', type: 'database' },
  'cassandra-driver': { name: 'Cassandra', logo: 'apachecassandra.svg', type: 'database' },
  '@aws-sdk/client-dynamodb': { name: 'DynamoDB', logo: 'amazondynamodb.svg', type: 'database' },
  '@google-cloud/firestore': { name: 'Firestore', logo: 'firebase.svg', type: 'database' },
  '@supabase/supabase-js': { name: 'Supabase', logo: 'supabase.svg', type: 'database' },
  '@planetscale/database': { name: 'PlanetScale', logo: 'planetscale.svg', type: 'database' },
  'faunadb': { name: 'FaunaDB', logo: 'fauna.svg', type: 'database' },
  '@cockroachdb/prisma-adapter': { name: 'CockroachDB', logo: 'cockroachlabs.svg', type: 'database' },
  'surrealdb.js': { name: 'SurrealDB', logo: 'surrealdb.svg', type: 'database' },
  'duckdb': { name: 'DuckDB', logo: 'duckdb.svg', type: 'database' },
  'axios': { name: 'Axios', logo: 'axios.svg', type: 'network' },
  'node-fetch': { name: 'Fetch', logo: 'brandfetch.svg', type: 'network' },
  'swr': { name: 'SWR', logo: 'swr.svg', type: 'network' },
  'got': { name: 'Got', logo: 'go.svg', type: 'network' },
  '@grpc/grpc-js': { name: 'gRPC', logo: 'grpc.svg', type: 'network' },
  'openapi': { name: 'OpenAPI', logo: 'openapiinitiative.svg', type: 'network' },
  'superagent': { name: 'SuperAgent', logo: 'superagent.svg', type: 'network' },
  'auth0': { name: 'Auth0', logo: 'auth0.svg', type: 'auth' },
  '@clerk/nextjs': { name: 'Clerk', logo: 'clerk.svg', type: 'auth' },
  '@supabase/auth-helpers-nextjs': { name: 'Supabase Auth', logo: 'supabase.svg', type: 'auth' },
  'firebase': { name: 'Firebase Auth', logo: 'firebase.svg', type: 'auth' },
  'next-auth': { name: 'NextAuth', logo: 'nextdotjs.svg', type: 'auth' },
  'jsonwebtoken': { name: 'JWT', logo: 'jsonwebtokens.svg', type: 'auth' },
  'passport': { name: 'Passport.js', logo: 'passport.svg', type: 'auth' },
  'bcrypt': { name: 'bcrypt', logo: 'bcrypt.svg', type: 'auth' },
  'argon2': { name: 'argon2', logo: 'argo.svg', type: 'auth' },
  'keycloak-js': { name: 'Keycloak', logo: 'keycloak.svg', type: 'auth' },
  'openai': { name: 'OpenAI SDK', logo: 'openai.svg', type: 'ai' },
  'langchain': { name: 'LangChain', logo: 'langchain.svg', type: 'ai' },
  '@tensorflow/tfjs': { name: 'TensorFlow.js', logo: 'tensorflow.svg', type: 'ai' },
  '@huggingface/inference': { name: 'HuggingFace', logo: 'huggingface.svg', type: 'ai' },
  'replicate': { name: 'Replicate', logo: 'replicate.svg', type: 'ai' },
  'ai': { name: 'Vercel AI SDK', logo: 'vercel.svg', type: 'ai' },
  '@xenova/transformers': { name: 'Transformers.js', logo: 'transformers.svg', type: 'ai' },
  'github-actions': { name: 'GitHub Actions', logo: 'githubactions.svg', type: 'ci' },
  'gitlab-ci': { name: 'GitLab CI', logo: 'gitlab.svg', type: 'ci' },
  'circleci': { name: 'CircleCI', logo: 'circleci.svg', type: 'ci' },
  'travis-ci': { name: 'Travis CI', logo: 'travisci.svg', type: 'ci' },
  'jenkins': { name: 'Jenkins', logo: 'jenkins.svg', type: 'ci' },
  'docker': { name: 'Docker', logo: 'docker.svg', type: 'container' },
  'docker-compose': { name: 'Docker Compose', logo: 'docker.svg', type: 'container' },
  'kubernetes': { name: 'Kubernetes', logo: 'kubernetes.svg', type: 'container' },
  'terraform': { name: 'Terraform', logo: 'terraform.svg', type: 'devops' },
  'ansible': { name: 'Ansible', logo: 'ansible.svg', type: 'devops' },
  '@pulumi/pulumi': { name: 'Pulumi', logo: 'pulumi.svg', type: 'devops' },
  'serverless': { name: 'Serverless Framework', logo: 'serverless.svg', type: 'devops' },
  'aws-sdk': { name: 'AWS', logo: 'amazonwebservices.svg', type: 'cloud' },
  '@azure/core-client': { name: 'Azure', logo: 'microsoftazure.svg', type: 'cloud' },
  '@google-cloud/storage': { name: 'Google Cloud', logo: 'googlecloud.svg', type: 'cloud' },
  'vercel': { name: 'Vercel', logo: 'vercel.svg', type: 'hosting' },
  'netlify': { name: 'Netlify', logo: 'netlify.svg', type: 'hosting' },
  '@railway/cli': { name: 'Railway', logo: 'railway.svg', type: 'hosting' },
  'render': { name: 'Render', logo: 'render.svg', type: 'hosting' },
  '@cloudflare/workers-types': { name: 'Cloudflare', logo: 'cloudflare.svg', type: 'cloud' },
  'eslint': { name: 'ESLint', logo: 'eslint.svg', type: 'lint' },
  'prettier': { name: 'Prettier', logo: 'prettier.svg', type: 'format' },
  'husky': { name: 'Husky', logo: 'husqvarna.svg', type: 'lint' },
  'lint-staged': { name: 'Lint-staged', logo: 'lintstaged.svg', type: 'lint' },
  'commitizen': { name: 'Commitizen', logo: 'commitizen.svg', type: 'lint' },
  '@commitlint/cli': { name: 'Commitlint', logo: 'commitlint.svg', type: 'lint' },
  'npm': { name: 'npm', logo: 'npm.svg', type: 'package' },
  'pnpm': { name: 'pnpm', logo: 'pnpm.svg', type: 'package' },
  'yarn': { name: 'Yarn', logo: 'yarn.svg', type: 'package' },
  '@11ty/eleventy': { name: '11ty', logo: 'eleventy.svg', type: 'ssg' },
  'hugo': { name: 'Hugo', logo: 'hugo.svg', type: 'ssg' },
  'jekyll': { name: 'Jekyll', logo: 'jekyll.svg', type: 'ssg' },
  'gatsby': { name: 'Gatsby', logo: 'gatsby.svg', type: 'ssg' },
  'wordpress': { name: 'WordPress', logo: 'wordpress.svg', type: 'cms' },
  '@shopify/shopify-api': { name: 'Shopify', logo: 'shopify.svg', type: 'cms' },
  '@sanity/client': { name: 'Sanity', logo: 'sanity.svg', type: 'cms' },
  'contentful': { name: 'Contentful', logo: 'contentful.svg', type: 'cms' },
  '@strapi/strapi': { name: 'Strapi', logo: 'strapi.svg', type: 'cms' },
  'ghost': { name: 'Ghost', logo: 'ghost.svg', type: 'cms' },
  '@keystone-6/core': { name: 'KeystoneJS', logo: 'keystone.svg', type: 'cms' },
  'directus': { name: 'Directus', logo: 'directus.svg', type: 'cms' },
  'turborepo': { name: 'TurboRepo', logo: 'turborepo.svg', type: 'automation' },
  'nx': { name: 'Nx', logo: 'nx.svg', type: 'automation' },
  'lerna': { name: 'Lerna', logo: 'lerna.svg', type: 'automation' },
  '@changesets/cli': { name: 'Changesets', logo: 'fallback/changesets.svg', type: 'automation' },
  'react-native': { name: 'React Native', logo: 'react.svg', type: 'mobile' },
  'expo': { name: 'Expo', logo: 'expo.svg', type: 'mobile' },
  'flutter': { name: 'Flutter', logo: 'flutter.svg', type: 'mobile' },
  '@ionic/angular': { name: 'Ionic', logo: 'ionic.svg', type: 'mobile' },
  '@capacitor/core': { name: 'Capacitor', logo: 'capacitor.svg', type: 'mobile' },
  'lodash': { name: 'Lodash', logo: 'lodash.svg', type: 'utility' },
  'dayjs': { name: 'Day.js', logo: 'dayjs.svg', type: 'utility' },
  'moment': { name: 'Moment.js', logo: 'moment.svg', type: 'utility' },
  'zod': { name: 'Zod', logo: 'zod.svg', type: 'utility' },
  'yup': { name: 'Yup', logo: 'pyup.svg', type: 'utility' },
  'joi': { name: 'Joi', logo: 'joi.svg', type: 'utility' },
  'rxjs': { name: 'RxJS', logo: 'reactivex.svg', type: 'utility' },
  'three': { name: 'Three.js', logo: 'threedotjs.svg', type: 'utility' },
  'leaflet': { name: 'Leaflet', logo: 'leaflet.svg', type: 'utility' },
  'd3': { name: 'D3.js', logo: 'd3.svg', type: 'utility' },
  'stripe': { name: 'Stripe', logo: 'stripe.svg', type: 'payment' },
  '@paypal/checkout-server-sdk': { name: 'PayPal SDK', logo: 'paypal.svg', type: 'payment' },
  '@lemonsqueezy/lemonsqueezy.js': { name: 'LemonSqueezy', logo: 'fallback/lemonsqueezy.svg', type: 'payment' }
};
